---

# Order. This is the main object.
order:
  # the field that uniquely identifies the domain / type
  idField: orderNumber
  # reference field - for sorting new values
  refField: localPlacedDate
  # Additional sort fields
  sortFields:
    orderNumber: ASC
  # List of source tables for this type
  tables:
    # cpOrder
    cpOrder:
      as: "cpOrder" # 'AS' in the select query
      # Not used for now ...
      primaryKeyFields:
        - orderNumber
    # cpOrderDetails
    cpOrderDetails:
      as: "cpOrderDetails"
      join: # INNER | LEFT_OUTER for now
        type: "INNER"
        parentColumns:
        - "cpOrder.OrderDetailsId"
        childColumns:
        - "cpOrderDetails.OrderDetailsId"
  # Additional where filters
  whereFilters:
#    - "cpOrder.Status = 'PLACED'"
    - "cpOrder.CpPlacedDate > '2015-03-01 00:00:00.000'"
# Multiple update scenarios
#  update:
#    cancelled:
#      refField: cancelDate
#      whereFilter: "cpOrder.Status='CANCELLED' AND cpOrder.CancelDate > ${max:cancelDate:datetime}"
#    confirmed:
#      refField: localConfirmDate
#      whereFilter: "cpOrder.Status='CONFIRMED' AND cpOrder.cpConfirmDate > ${max:localConfirmDate:datetime}"
  # List of fields for this type
  fields:
    orderNumber:
      sqlExpression: "cpOrder.OrderNumber"
      type: STRING
    orderStatus:
      sqlExpression: "cpOrder.Status"
      type: STRING
    placedDate:
      sqlExpression: "cpOrder.PlacedDate"
      type: DATETIME
    confirmDate:
      sqlExpression: "cpOrder.ConfirmDate"
      type: DATETIME
    localPlacedDate:
      sqlExpression: "cpOrder.CpPlacedDate"
      type: DATETIME
    localConfirmDate:
      sqlExpression: "cpOrder.CpConfirmDate"
      type: DATETIME
    expiryDate:
      sqlExpression: "cpOrder.ExpiryDate"
      type: DATETIME
    cancelDate:
      sqlExpression: "cpOrder.CancelDate"
      type: DATETIME
    orderReference:
      sqlExpression: "cpOrder.OrderReference"
      type: STRING
    partnerCode:
      sqlExpression: "cpOrder.PartnerCode"
      type: STRING
    shippingMethodId:
      sqlExpression: "cpOrder.ShippingMethodId"
      type: STRING
    merchantCode:
      sqlExpression: "cpOrder.AccountReference"
      type: STRING
    hubId:
      sqlExpression: "cpOrder.HubId"
      type: STRING

# CONSIGNEE ADDRESS
order.consignee:
  # relation to the parent type: one object or an array of object; not required for the top level object
  # ONE | MANY
  parentRelation: ONE
  # the field that uniquely identifies the type
  idField: orderConsigneeId
  # List of source tables for this type
  tables:
    # cpOrderConsignee
    cpOrderConsignee:
      as: "cpOrderConsignee"
      primaryKeyFields:
        - orderConsigneeId
      join: # INNER | LEFT_OUTER for now
        type: "INNER"
        parentColumns:
        - "cpOrderDetails.OrderConsigneeId"
        childColumns:
        - "cpOrderConsignee.OrderConsigneeId"
    cpOrderAddress:
      as: "cpOrderAddress"
      primaryKeyFields:
        - orderAddressId
      join: # INNER | LEFT_OUTER
        type: "INNER"
        parentColumns:
        - "cpOrderConsignee.AddressId"
        childColumns:
        - "cpOrderAddress.AddressId"
  fields:
    orderConsigneeId:
      sqlExpression: "cpOrderConsignee.OrderConsigneeId"
      type: LONG
    consigneeNumber:
      sqlExpression: "cpOrderConsignee.ConsigneeNumber"
      type: STRING
    orderAddressId:
      sqlExpression: "cpOrderAddress.AddressId"
      type: LONG
    firstName:
      sqlExpression: "cpOrderAddress.FirstName"
      type: STRING
    lastName:
      sqlExpression: "cpOrderAddress.LastName"
      type: STRING
    middleName:
      sqlExpression: "cpOrderAddress.middleName"
      type: STRING
    name:
      sqlExpression: "cpOrderAddress.FirstName + ' ' + COALESCE(cpOrderAddress.MiddleName, '') + ' ' + cpOrderAddress.LastName"
      type: STRING
    street:
      sqlExpression: "COALESCE(cpOrderAddress.Street1, '') + ' ' + COALESCE(cpOrderAddress.Street2, '') + ' ' + COALESCE(cpOrderAddress.Street3, '')"
      type: STRING
    company:
      sqlExpression: "cpOrderAddress.Company"
      type: STRING
    email:
      sqlExpression: "cpOrderAddress.Email"
      type: STRING
    phoneNumber1:
      sqlExpression: "cpOrderAddress.PhoneNumber1"
      type: STRING
    phoneNumber2:
      sqlExpression: "cpOrderAddress.PhoneNumber2"
      type: STRING
    faxNumber:
      sqlExpression: "cpOrderAddress.FaxNumber"
      type: STRING
    postalCode:
      sqlExpression: "cpOrderAddress.PostalCode"
      type: STRING
    city:
      sqlExpression: "cpOrderAddress.City"
      type: STRING
    region:
      sqlExpression: "cpOrderAddress.Region"
      type: STRING
    countryCode:
      sqlExpression: "cpOrderAddress.Country"
      type: STRING
    buyerId:
      sqlExpression: "cpOrderAddress.BuyerId"
      type: STRING

# order.orderLines
order.orderLines:
  # relation to the parent type: one object or an array of object; not required for the top level object
  # ONE | MANY
  parentRelation: MANY
  # the field that uniquely identifies the type
  idField: orderDetailsLineId
  # List of tables, part of this type
  tables:
    # cpOrderDetailsLine
    cpOrderDetailsLine:
      as: "cpOrderDetailsLine"
      primaryKeyFields:
        - orderDetailsLineId
      join: # INNER | LEFT_OUTER
        type: "LEFT_OUTER"
        parentColumns:
        - "cpOrderDetails.OrderDetailsId"
        childColumns:
        - "cpOrderDetailsLine.OrderDetailsId"
    # cpOrderDetailsCommodity
    cpOrderDetailsCommodity:
      as: "cpOrderDetailsCommodity"
      primaryKeyFields:
        - orderDetailsCommodityId
      join: # ONE_TO_ONE, ZERO_TO_ONE, ONE_TO_MANY, ZERO_TO_MANY; default is ONE_TO_ONE
        type: "INNER"
        parentColumns:
        - "cpOrderDetailsLine.OrderDetailsCommodityId"
        childColumns:
        - "cpOrderDetailsCommodity.OrderDetailsCommodityId"
  fields:
    orderDetailsLineId:
      sqlExpression: "cpOrderDetailsLine.OrderDetailsLineId"
      type: LONG
    countryOfOriginCode:
      sqlExpression: "cpOrderDetailsLine.CountryOfOrigin"
      type: STRING
    quantity:
      sqlExpression: "cpOrderDetailsLine.Quantity"
      type: SHORT
    orderDetailsCommodityId:
      sqlExpression: "cpOrderDetailsCommodity.OrderDetailsCommodityId"
      type: LONG
    sku:
      sqlExpression: "cpOrderDetailsCommodity.SKU"
      type: STRING
    name:
      sqlExpression: "cpOrderDetailsCommodity.Name"
      type: STRING
    url:
      sqlExpression: "cpOrderDetailsCommodity.URL"
      type: STRING
    hsCode:
      sqlExpression: "cpOrderDetailsCommodity.HSCode"
      type: STRING
    categoryPath:
      sqlExpression: "cpOrderDetailsCommodity.CategoryPath"
      type: STRING
# INBOUND PARCEL
order.inboundParcels:
  # relation to the parent type: one object or an array of object; not required for the top level object
  # ONE | MANY
  parentRelation: MANY
  # the field that uniquely identifies the type
  idField: inboundParcelNumber
  tables:
    cpInboundParcel:
      as: "cpInboundParcel"
      primaryKeyFields:
      - inboundParcelNumber
      join:
        type: LEFT_OUTER
        parentColumns:
        - "cpOrder.OrderNumber"
        childColumns:
        - "cpInboundParcel.OrderNumber"
# filter by something - only real inbound parcels
  fields:
    inboundParcelNumber:
      sqlExpression: "cpInboundParcel.InboundParcelNumber"
      type: STRING
    parentInboundParcelNumber:
      sqlExpression: "cpInboundParcel.ParentInboundParcelNumber"
      type: STRING
    status:
      sqlExpression: "cpInboundParcel.Status"
      type: STRING
    placedDate:
      sqlExpression: "cpInboundParcel.PlacedDate"
      type: DATETIME
    cancellationDate:
      sqlExpression: "cpInboundParcel.CancellationDate"
      type: DATETIME
    processedDate:
      sqlExpression: "cpInboundParcel.ProcessedDate"
      type: DATETIME
    inboundCarrierId:
      sqlExpression: "cpInboundParcel.InboundCarrierID"
      type: STRING
    inboundShippingMethodId:
      sqlExpression: "cpInboundParcel.InboundShippingMethodID"
      type: STRING
    parcelReference:
      sqlExpression: "cpInboundParcel.ParcelReference"
      type: STRING
    orderNumber:
      sqlExpression: "cpInboundParcel.OrderNumber"
      type: STRING
    parcelIdentification:
      sqlExpression: "cpInboundParcel.Identification"
      type: STRING
# inbound parcel lines
order.inboundParcels.inboundParcelLines:
  # relation to the parent type: one object or an array of object; not required for the top level object
  # ONE | MANY
  parentRelation: MANY
  # the field that uniquely identifies the type
  idField: lineId
  tables:
    cpInboundParcelLine:
      as: "cpInboundParcelLine"
      primaryKeyFields:
      - lineId
      join:
        type: "LEFT_OUTER"
        parentColumns:
        - "cpInboundParcel.InboundParcelNumber"
        childColumns:
        - "cpInboundParcelLine.InboundParcelNumber"
    cpInboundParcelCommodity:
      as: "cpInboundParcelCommodity"
      primaryKeyFields:
      - inboundParcelCommodityId
      join:
        type: "LEFT_OUTER"
        parentColumns:
        - "cpInboundParcelLine.InboundParcelCommodityId"
        childColumns:
        - "cpInboundParcelCommodity.InboundParcelCommodityId"
  fields:
    # Inbound parcel line ID
    inboundParcelNumber:
      sqlExpression: "cpInboundParcelLine.InboundParcelNumber"
      type: STRING
    lineId:
      sqlExpression: "cpInboundParcelLine.InboundParcelLineId"
      type: LONG
    originCountryCode:
      sqlExpression: "cpInboundParcelLine.CountryOfOrigin"
      type: STRING
    quantity:
      sqlExpression: "cpInboundParcelLine.Quantity"
      type: SHORT
    # Commodity
    inboundParcelCommodityId:
      sqlExpression: "cpInboundParcelCommodity.InboundParcelCommodityId"
      type: LONG
    sku:
      sqlExpression: "cpInboundParcelCommodity.SKU"
      type: STRING
    name:
      sqlExpression: "cpInboundParcelCommodity.Name"
      type: STRING
    url:
      sqlExpression: "cpInboundParcelCommodity.URL"
      type: STRING
    hsCode:
      sqlExpression: "cpInboundParcelCommodity.HSCode"
      type: STRING
    hsCodeSource:
      sqlExpression: "cpInboundParcelCommodity.HSCodeSource"
      type: STRING
    categoryPath:
      sqlExpression: "cpInboundParcelCommodity.CategoryPath"
      type: STRING
